version: '3.8'

services:
  messaging-service:
    build:
      context: /messaging-service/
      dockerfile: Dockerfile
    image: messaging-service:latest
    container_name: messaging-service
    environment:
      - DATABASE_HOST=postgres # unused right now
      - DATABASE_PORT=5432 # unused right now
      - DATABASE_USER=postgres # unused right now
      - DATABASE_PASSWORD=postgres # unused right now
      - DATABASE_NAME=messaging_db # unused right now
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messaging_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
